files:
  - source: /modules/johncms/admin/locale/admin.pot
    translation: /modules/johncms/admin/locale/%two_letters_code%.po
  - source: /modules/johncms/auth/locale/auth.pot
    translation: /modules/johncms/auth/locale/%two_letters_code%.po
  - source: /modules/johncms/community/locale/community.pot
    translation: /modules/johncms/community/locale/%two_letters_code%.po
  - source: /modules/johncms/downloads/locale/downloads.pot
    translation: /modules/johncms/downloads/locale/%two_letters_code%.po
  - source: /modules/johncms/forum/locale/forum.pot
    translation: /modules/johncms/forum/locale/%two_letters_code%.po
  - source: /modules/johncms/guestbook/locale/guestbook.pot
    translation: /modules/johncms/guestbook/locale/%two_letters_code%.po
  - source: /modules/johncms/help/locale/help.pot
    translation: /modules/johncms/help/locale/%two_letters_code%.po
  - source: /modules/johncms/homepage/locale/homepage.pot
    translation: /modules/johncms/homepage/locale/%two_letters_code%.po
  - source: /modules/johncms/library/locale/library.pot
    translation: /modules/johncms/library/locale/%two_letters_code%.po
  - source: /modules/johncms/mail/locale/mail.pot
    translation: /modules/johncms/mail/locale/%two_letters_code%.po
  - source: /modules/johncms/news/locale/news.pot
    translation: /modules/johncms/news/locale/%two_letters_code%.po
  - source: /modules/johncms/online/locale/online.pot
    translation: /modules/johncms/online/locale/%two_letters_code%.po
  - source: /modules/johncms/personal/locale/profile.pot
    translation: /modules/johncms/personal/locale/%two_letters_code%.po
  - source: /system/locale/system.pot
    translation: /system/locale/%two_letters_code%.po
  - source: /public/install/locale/install.pot
    translation: /public/install/locale/%two_letters_code%.po
