version: "3.9"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker-configs/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
      - ./docker-configs/logs/nginx/:/var/log/nginx/
   # restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - php
  php:
    build: ./docker-configs/php
    volumes:
      - .:/var/www/html
     # - ./docker-configs/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    volumes:
      - dbdata:/var/lib/mysql
   # volumes:
    #  - ./docker-configs/mysql/import:/docker-entrypoint-initdb.d
    #  - ./docker-configs/mysql/config:/etc/mysql/conf/conf.d
    #  - ./docker-configs/logs/mysql/:/var/log/mysql
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql
volumes:
  dbdata: