version: '3.8'
services:
  webserver:
    build: ./docker/general
    container_name: ubuntu.${APP_NAME:-johncms}
    depends_on:
      - mariadb
    volumes:
      - .:/var/www/html
    ports:
      - '${NGINX_HTTP_PORT:-8000}:80'
      - '${NGINX_HTTP_PORT:-8001}:443'
    networks:
      - default
  mariadb:
    image: 'mysql:8'
    container_name: mariadb.${APP_NAME:-johncms}
    ports:
      - '${FORWARD_DB_PORT:-}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-johncms}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE:-johncms}'
      MYSQL_USER: '${DB_USERNAME:-johncms}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './docker/mariadb/data:/var/lib/mysql'
    networks:
      - default

