name: Deploy To Server

on:
  # Deploy on merge to main
  push:
    branches: [ stage9 ]
#  # Manually deploy branch
#  workflow_dispatch:
#    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer update

      - name: Install SSH key to Server
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_STAGE }}
          name: github-actions
          known_hosts: 'random-placeholder-value-replaced-by-keyscan-below'
          config: |
            host stage.oldfag.top
              IdentityFile ~/.ssh/github-actions
              IdentitiesOnly yes
              ForwardAgent yes
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST_STAGE }}
      - name: Install NPM dependencies
        run: npm install
