name: Deploy To Server

on:
  # Deploy on merge to main
  push:
    branches: [ stage9 ]
#  # Manually deploy branch
#  workflow_dispatch:
#    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install SSH key to Server
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_STAGE }}
          name: github-actions
          known_hosts: 'random-placeholder-value-replaced-by-keyscan-below'
          config: |
            host stage.oldfag.top
              IdentityFile ~/.ssh/github-actions
              IdentitiesOnly yes
              ForwardAgent yes
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST_STAGE }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_STAGE }}
          key: ${{ secrets.SSH_KEY_STAGE }}
          username: ${{ secrets.SSH_USERNAME_STAGE }}
          script: |
            sudo apt update && sudo apt upgrade -y && sudo apt install -y composer npm php7.4 php7.4-fpm php7.4-dev php7.4-cli php7.4-gd php7.4-mysql php7.4-opcache php7.4-xml php7.4-xmlrpc php7.4-zip
            rm -Rf /var/www/html/*
            mkdir /var/www/html/stage9
            cd /var/www/html/stage9
            git clone git@github.com:Chifth/johncms.git -b stage9
            cd johncms
